version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  # See workflows/test-e2e.yml for the current list of k8s namespaces available for integration testing.
  # Presently, there are only 2.
  # Keeping the open PR limit low at 4 so that when automatically rebasing, 4 concurrent Dependabot PR integration test
  # runs all stand a chance at success rather than some being guaranteed to time out waiting for an available namespace.
  open-pull-requests-limit: 4
  commit-message:
    prefix: "[DCJ-304-npm]"
  groups:
    # We group minor and patch updates together because they are unexpected to break things.
    # Major updates will be PR-ed individually: they are more likely to need developer intervention.
    npm-minor-patch-dependencies:
      patterns:
        - "*"
      update-types:
        - "minor"
        - "patch"
  ignore:
  # @types/node version should stay in sync with .node_version and our Dockerfiles
  - dependency-name: "@types/node"
  # newer versions of prettier seem to format the code in a way that is incompatible with eslint (DR-2953)
  # more generally, eslint and prettier upgrades are likely to need developer intervention
  - dependency-name: "@typescript-eslint/eslint-plugin"
  - dependency-name: "eslint-config-prettier"
  - dependency-name: "eslint-plugin-prettier"
  - dependency-name: "prettier"
  # newer versions of material ui (MUI) cause our styling to not respect theming or straight up break the UI (DR-2952)
  - dependency-name: "@mui/*"
  # @mui/styles is incompatible with react 18, we should replace @mui/styles with tss-react (DR-3428)
  # more generally, react 18 / redux 8 upgrades are a large lift (DR-2799)
  - dependency-name: "@reduxjs/tookit"
    update-types: [ "version-update:semver-major" ]
  - dependency-name: "@testing-library/react"
    update-types: [ "version-update:semver-major" ]
  - dependency-name: "@types/react*"                # @types/react, @types/react-dom, etc.
    update-types: [ "version-update:semver-major" ]
  - dependency-name: "react*"                       # react, react-dom, etc.
    update-types: [ "version-update:semver-major" ]
  - dependency-name: "redux"
    update-types: [ "version-update:semver-major" ]
  # later versions of history yield a warning on npm install (DR-3432)
  - dependency-name: "history"
    update-types: [ "version-update:semver-major" ]
  # later versions of vite break e2e tests (DR-3433)
  - dependency-name: "vite"
    update-types: [ "version-update:semver-major" ]
