name: Dependabot E2E Tests
on:
  pull_request_target:
    branches:
      - develop
    paths:
      - '!*'
      - 'src/**'
      - 'package.json'
      - 'cypress.json'
      - 'cypress/**'
      - 'Dockerfile'
      - 'Dockerfile.direct'
      - 'config-overrides.js'
      - '.github/workflows/test-e2e.yml'
jobs:
  check_dependabot:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Dependabot PR"
  e2e_test:
    needs: check_dependabot
    uses: 'DataBiosphere/jade-data-repo-ui/.github/workflows/reusable-e2e-test.yml@sh-dr-2786-branch'
