name: Update devs ui image
on:
  workflow_dispatch: {}
  push:
    branches:
      - develop
    paths:
      - '!*'
      - 'src/**'
      - 'package.json'
      - 'cypress.json'
      - 'cypress/**'
      - 'Dockerfile'
      - '.github/workflows/dev-image-update.yaml'
env:
  GCR_GOOGLE_PROJECT: 'broad-jade-dev'
  google_sdk_version: '290.0.1'
  DEV_PROJECT: broad-jade-dev
  # This must be defined for the bash redirection
  GOOGLE_APPLICATION_CREDENTIALS: 'jade-dev-account.json'
  # This must be defined for the bash redirection
  GOOGLE_SA_CERT: 'jade-dev-account.pem'

jobs:
  update_image:
    outputs:
      ui_image_tag: ${{ steps.bumperstep.outputs.tag }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    if: "!contains( github.event.sender.login, 'broadbot')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: develop
          token: ${{ secrets.BROADBOT_TOKEN }}
      - name: 'Bump the tag to a new version'
        uses: broadinstitute/datarepo-actions/actions/main@0.74.0
        id: bumperstep
        with:
          actions_subcommand: 'bumper'
          sa_b64_credentials: ${{ secrets.SA_B64_CREDENTIALS }}
          version_file_path: package.json
          version_variable_name: version
          GITHUB_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
      - name: 'Get gcp credentials'
        uses: broadinstitute/datarepo-actions/actions/main@0.74.0
        with:
          actions_subcommand: 'skip'
          sa_b64_credentials: ${{ secrets.SA_B64_CREDENTIALS }}
      - name: 'Pull down new tags'
        run: git fetch --all --tags
      - name: 'Get Previous tag'
        id: uiprevioustag
        uses: 'broadinstitute/github-action-get-previous-tag@master'
        env:
          GITHUB_TOKEN: '${{ secrets.BROADBOT_TOKEN }}'
      - name: Build nmp build for new ui container
        run: |
          git pull
          GCR_TAG=$(git rev-parse --short HEAD)
          echo "GCR_TAG=$(echo ${GCR_TAG})" >> $GITHUB_ENV
      # Build the Docker image
      - name: Build docker container
        env:
          DISABLE_ESLINT_PLUGIN: true
        run: |
          rm -rf jade-dev-account.pem
          docker build -t "gcr.io/${GCR_GOOGLE_PROJECT}/jade-data-repo-ui:${GCR_TAG}" --build-arg CACHEBUST=$(date +%s) .
      # Push the Docker image to Google Container Registry
      - name: Publish and tag new docker container to GCR
        run: |
          gcloud auth activate-service-account --key-file jade-dev-account.json
          gcloud auth configure-docker --quiet
          docker push "gcr.io/${GCR_GOOGLE_PROJECT}/jade-data-repo-ui:${GCR_TAG}"
          gcloud container images \
            add-tag \
            "gcr.io/${GCR_GOOGLE_PROJECT}/jade-data-repo-ui:${GCR_TAG}" \
            "gcr.io/${GCR_GOOGLE_PROJECT}/jade-data-repo-ui:${PREV_TAG}" --quiet
          gcloud container images \
            add-tag \
            "gcr.io/${GCR_GOOGLE_PROJECT}/jade-data-repo-ui:${GCR_TAG}" \
            "gcr.io/${GCR_GOOGLE_PROJECT}/jade-data-repo-ui:${GCR_TAG}-develop" --quiet
        env:
          PREV_TAG: ${{ steps.uiprevioustag.outputs.tag }}
  update_dsp_image:
    # The purpose of this job is to push the constructed image and tags to DSP's artifact repository
    # Future work will migrate from TDR's artifact repository to the DSP location
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Auth to GCP
        id: "auth"
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/1038484894585/locations/global/workloadIdentityPools/github-wi-pool/providers/github-wi-provider"
          service_account: "dsp-artifact-registry-push@dsp-artifact-registry.iam.gserviceaccount.com"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Explicitly auth Docker for Artifact Registry
        run: gcloud auth configure-docker $GOOGLE_DOCKER_REPOSITORY --quiet
      - name: Construct docker image name and tags
        id: image-name
        shell: bash
        run: |
          NAME="${GOOGLE_DOCKER_REPOSITORY}/${GOOGLE_PROJECT}/${REPOSITORY_NAME}/${IMAGE_NAME}"
          TAGGED="${NAME}:${GCR_TAG}"
          echo "NAME: ${NAME}"
          echo "TAGGED: ${TAGGED}"
          echo "NAME=${NAME}" >> "$GITHUB_ENV"
          echo "TAGGED=${TAGGED}" >> "$GITHUB_ENV"
        env:
          GOOGLE_PROJECT: dsp-artifact-registry
          REPOSITORY_NAME: ${{ github.event.repository.name }}
          IMAGE_NAME: ${{ github.event.repository.name }}
          GOOGLE_DOCKER_REPOSITORY: us-central1-docker.pkg.dev
      - name: Build image
        run: |
          docker build -t "$TAGGED" .
      # Publish images
      - name: Push image
        run: |
          docker push "$TAGGED"
      - name: Add develop, and latest tags to Docker image
        if: github.event_name != 'pull_request'
        shell: bash
        run: |
          gcloud artifacts docker tags add \
            "$TAGGED-develop" \
            "$NAME:latest"
  helm_tag_bump:
    needs: update_image
    uses: ./.github/workflows/helmtagbump.yaml
    secrets: inherit
  cherry_pick_image_to_production_gcr:
    needs: update_image
    uses: DataBiosphere/jade-data-repo/.github/workflows/cherry-pick-image.yaml@2.201.0
    secrets: inherit
    with:
      gcr_tag: ${{ needs.update_image.outputs.ui_image_tag }}
      source_gcr_url: 'gcr.io/broad-jade-dev/jade-data-repo-ui'
      target_gcr_url: 'gcr.io/datarepo-public-gcr/jade-data-repo-ui'
