name: Update devs ui image
on:
  push:
    branches:
      - develop
    paths:
      - '!*'
      - 'src/**'
      - 'package.json'
      - 'cypress.json'
      - 'cypress/**'
      - 'Dockerfile'
      - 'config-overrides.js'
      - '.github/workflows/helmtagbump.yaml'
env:
  gcr_google_project: "broad-jade-dev"
  google_sdk_version: "290.0.1"
  DEV_PROJECT: broad-jade-dev

jobs:
# new integration image updater
  integration_helm_tag_update:
    strategy:
      matrix:
        namespaces: [integration-1,integration-2,integration-3,integration-4,integration-5,integration-6]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: develop
      - name: 'Checkout datarepo-helm-definitions repo'
        uses: actions/checkout@v2
        with:
          repository: 'broadinstitute/datarepo-helm-definitions'
          token: ${{ secrets.HELM_REPO_TOKEN }}
          path: datarepo-helm-definitions
          fetch-depth: 0
      - name: 'Get git hash short'
        run: |
          echo 'GCR_TAG<<EOF' >> $GITHUB_ENV
          git rev-parse --short HEAD >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: "Find and replace Datarepo ui helm definition value tag"
        uses: docker://mikefarah/yq:latest
        with:
          args: yq w -i datarepo-helm-definitions/integration/${{ matrix.namespaces }}/datarepo-ui.yaml image.tag ${{ GCR_TAG }}
      - name: push commit to datarepo-helm-definitions
        run: |
          git config --global user.email "robot@jade.team"
          git config --global user.name "imagetagbot"
          git add integration/
          git commit -m "Updated integration tag - ${GCR_TAG}"
          git push origin master
      - name: Slack job status
        if: always()
        uses: broadinstitute/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Integration Test
          only_mention_fail: smark,myessail
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
