name: Update integration ui helm image tag
on:
  workflow_dispatch: {}
jobs:
# new integration image updater
  integration_helm_tag_update:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: develop
      - name: 'Get Previous tag'
        id: uiprevioustag
        uses: "broadinstitute/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: 'Checkout datarepo-helm-definitions repo'
        uses: actions/checkout@v2
        with:
          repository: 'broadinstitute/datarepo-helm-definitions'
          token: ${{ secrets.BROADBOT_TOKEN}}
          path: datarepo-helm-definitions
      - name: "integration-1 find and replace"
        uses: docker://mikefarah/yq:3
        with:
          args: yq w -i datarepo-helm-definitions/integration/integration-1/datarepo-ui.yaml image.tag ${{ steps.uiprevioustag.outputs.tag }}"
      - name: "integration-2 find and replace"
        uses: docker://mikefarah/yq:3
        with:
          args: yq w -i datarepo-helm-definitions/integration/integration-2/datarepo-ui.yaml image.tag ${{ steps.uiprevioustag.outputs.tag }}"
      - name: "integration-3 find and replace"
        uses: docker://mikefarah/yq:3
        with:
          args: yq w -i datarepo-helm-definitions/integration/integration-3/datarepo-ui.yaml image.tag ${{ steps.uiprevioustag.outputs.tag }}"
      - name: "integration-4 find and replace"
        uses: docker://mikefarah/yq:3
        with:
          args: yq w -i datarepo-helm-definitions/integration/integration-4/datarepo-ui.yaml image.tag ${{ steps.uiprevioustag.outputs.tag }}"
      - name: "integration-5 find and replace"
        uses: docker://mikefarah/yq:3
        with:
          args: yq w -i datarepo-helm-definitions/integration/integration-5/datarepo-ui.yaml image.tag ${{ steps.uiprevioustag.outputs.tag }}"
      - name: "integration-6 find and replace"
        uses: docker://mikefarah/yq:3
        with:
          args: yq w -i datarepo-helm-definitions/integration/integration-6/datarepo-ui.yaml image.tag ${{ steps.uiprevioustag.outputs.tag }}"
      - name: "[datarepo-helm-definitions] Merge chart version update"
        uses: broadinstitute/datarepo-actions/actions/merger@0.38.0
        env:
          COMMIT_MESSAGE: "Datarepo ui tag version update: ${{ steps.uiprevioustag.outputs.tag }}"
          GITHUB_REPO: datarepo-helm-definitions
          SWITCH_DIRECTORIES: true
          MERGE_BRANCH: master
      - name: Slack job status
        if: always()
        uses: broadinstitute/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: ui_helm_bumper
          only_mention_fail: smark,myessail
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  ui_helm_default_chart_tag:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: develop
      - name: 'Get Previous tag'
        id: uiprevioustag
        uses: "broadinstitute/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: 'Checkout datarepo-helm repo'
        uses: actions/checkout@v2
        with:
          repository: 'broadinstitute/datarepo-helm'
          token: ${{ secrets.BROADBOT_TOKEN }}
          path: datarepo-helm
      - name: "ui chart default tag find and replace"
        uses: docker://mikefarah/yq:3
        with:
          args: yq w -i datarepo-helm/charts/datarepo-ui/values.yaml image.tag ${{ steps.uiprevioustag.outputs.tag }}"
      - name: "bump ui chart appVersion"
        uses: docker://mikefarah/yq:3
        with:
          args: yq w -i datarepo-helm/charts/datarepo-ui/Chart.yaml appVersion ${{ steps.uiprevioustag.outputs.tag }}"
      - name: "get new chart verion"
        id: new_version
        run: |
          version=$(docker run --rm -v ${PWD}:/workdir mikefarah/yq:3 yq r datarepo-helm/charts/datarepo-ui/Chart.yaml 'version')
          a=(`echo $version | sed 's/\./ /g'`)
          ((a[2]++))
          printf "increase default ui version: ${a[2]}\n\n"
          new_version="${a[0]}.${a[1]}.${a[2]}"
          echo "::set-output name=new_version::$new_version"
      - name: "bump ui chart Version"
        uses: docker://mikefarah/yq:3
        with:
          args: yq w -i datarepo-helm/charts/datarepo-ui/Chart.yaml version ${{ steps.new_version.outputs.new_version }}"
      - name: "[datarepo-helm] Merge chart version update"
        uses: broadinstitute/datarepo-actions/actions/merger@0.38.0
        env:
          COMMIT_MESSAGE: "Datarepo ui tag version update: ${{ steps.uiprevioustag.outputs.tag }}"
          GITHUB_REPO: datarepo-helm
          SWITCH_DIRECTORIES: true
          MERGE_BRANCH: master
      - name: Slack job status
        if: always()
        uses: broadinstitute/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: ui_helm_bumper
          only_mention_fail: smark,myessail
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
