name: Update integration ui helm image tag
on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  ui_helm_default_chart_tag:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: develop
      - name: 'Get Previous tag'
        id: uiprevioustag
        run: |
          TAG=$(git for-each-ref --sort=-creatordate --count 1 --format="%(refname:short)" "refs/tags/")
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
      - name: 'Checkout datarepo-helm repo'
        uses: actions/checkout@v3
        with:
          repository: 'broadinstitute/datarepo-helm'
          token: ${{ secrets.BROADBOT_TOKEN }}
          path: datarepo-helm
      - name: 'ui chart default tag find and replace'
        uses: docker://mikefarah/yq:3
        with:
          args: yq w -i datarepo-helm/charts/datarepo-ui/values.yaml image.tag ${{ steps.uiprevioustag.outputs.tag }}"
      - name: 'bump ui chart appVersion'
        uses: docker://mikefarah/yq:3
        with:
          args: yq w -i datarepo-helm/charts/datarepo-ui/Chart.yaml appVersion ${{ steps.uiprevioustag.outputs.tag }}"
      - name: 'get new chart verion'
        id: new_version
        run: |
          version=$(docker run --rm -v ${PWD}:/workdir mikefarah/yq:3 yq r datarepo-helm/charts/datarepo-ui/Chart.yaml 'version')
          a=(`echo $version | sed 's/\./ /g'`)
          ((a[2]++))
          printf "increase default ui version: ${a[2]}\n\n"
          new_version="${a[0]}.${a[1]}.${a[2]}"
          echo "new_version=${new_version}" >> $GITHUB_OUTPUT
      - name: 'bump ui chart Version'
        uses: docker://mikefarah/yq:3
        with:
          args: yq w -i datarepo-helm/charts/datarepo-ui/Chart.yaml version ${{ steps.new_version.outputs.new_version }}"
      - name: '[datarepo-helm] Merge chart version update'
        uses: broadinstitute/datarepo-actions/actions/merger@0.74.0
        env:
          COMMIT_MESSAGE: 'Datarepo ui tag version update: ${{ steps.uiprevioustag.outputs.tag }}'
          GITHUB_REPO: datarepo-helm
          SWITCH_DIRECTORIES: true
          MERGE_BRANCH: master
