name: Update integration ui helm image tag
on:
  workflow_dispatch: {}
jobs:
# new integration image updater
  integration_helm_tag_update:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: develop
      - name: 'Get Previous tag'
        id: uiprevioustag
        uses: "broadinstitute/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: 'Checkout datarepo-helm-definitions repo'
        uses: actions/checkout@v2
        with:
          repository: 'broadinstitute/datarepo-helm-definitions'
          token: ${{ secrets.HELM_REPO_TOKEN }}
          path: datarepo-helm-definitions
      - name: "integration-1 find and replace"
        uses: docker://mikefarah/yq:latest
        with:
          args: yq w -i datarepo-helm-definitions/integration/integration-1/datarepo-ui.yaml image.tag ${{ steps.uiprevioustag.outputs.tag }}"
      - name: "integration-2 find and replace"
        uses: docker://mikefarah/yq:latest
        with:
          args: yq w -i datarepo-helm-definitions/integration/integration-2/datarepo-ui.yaml image.tag ${{ steps.uiprevioustag.outputs.tag }}"
      - name: "integration-3 find and replace"
        uses: docker://mikefarah/yq:latest
        with:
          args: yq w -i datarepo-helm-definitions/integration/integration-3/datarepo-ui.yaml image.tag ${{ steps.uiprevioustag.outputs.tag }}"
      - name: "integration-4 find and replace"
        uses: docker://mikefarah/yq:latest
        with:
          args: yq w -i datarepo-helm-definitions/integration/integration-4/datarepo-ui.yaml image.tag ${{ steps.uiprevioustag.outputs.tag }}"
      - name: "integration-5 find and replace"
        uses: docker://mikefarah/yq:latest
        with:
          args: yq w -i datarepo-helm-definitions/integration/integration-5/datarepo-ui.yaml image.tag ${{ steps.uiprevioustag.outputs.tag }}"
      - name: "integration-6 find and replace"
        uses: docker://mikefarah/yq:latest
        with:
          args: yq w -i datarepo-helm-definitions/integration/integration-6/datarepo-ui.yaml image.tag ${{ steps.uiprevioustag.outputs.tag }}"
      - name: Create pull request
        uses: broadinstitute/create-pull-request@v3 # forked from peter-evans/create-pull-request
        id: create-pr
        with:
          token: ${{ secrets.HELM_DEF_REPO_TOKEN }}
          path: datarepo-helm-definitions
          commit-message: "Datarepo ui tag version update: ${{ steps.uiprevioustag.outputs.tag }}"
          committer: datarepo-bot <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: "Datarepo version update: ${{ steps.uiprevioustag.outputs.tag }}"
          branch: "version-update/${{ steps.uiprevioustag.outputs.tag }}"
          body: |
            Update versions in **${{ steps.uiprevioustag.outputs.tag }}**.
            *Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).*
          labels: "datarepo,automerge,version-update"
      - name: Slack job status
        if: always()
        uses: broadinstitute/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: ui_helm_bumper
          only_mention_fail: smark,myessail
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
