name: Regular E2E Tests
on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - develop
    paths:
      - '!*'
      - 'src/**'
      - 'package.json'
      - 'cypress.json'
      - 'cypress/**'
      - 'Dockerfile'
      - 'Dockerfile.direct'
      - 'config-overrides.js'
      - '.github/workflows/test-e2e.yml'
  schedule:
    - cron: '0 4 * * *' # run at 4 AM UTC, 12PM EST.
jobs:
  dependabot-check:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - run: echo "PR NOT created by Dependabot"