name: Test Workflow Run
on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["Regular E2E Tests"]
    branches: [sh-dr-2786-dependabot-secret]
    types: 
      - completed
jobs:
  do-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: echo "Successful Trigger via workflow_run"