name: e2e
on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - develop
    paths:
      - '!*'
      - 'src/**'
      - 'package.json'
      - 'cypress.json'
      - 'cypress/**'
      - 'Dockerfile'
      - 'Dockerfile.direct'
      - 'config-overrides.js'
      - '.github/workflows/test-e2e.yml'
  schedule:
    - cron: '0 4 * * *' # run at 4 AM UTC, 12PM EST.
jobs:
  check_dependabot:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Not a dependabot PR"
  e2e_test:
    needs: check_dependabot
    uses: 'DataBiosphere/jade-data-repo-ui/.github/workflows/reusable-e2e-test.yml@sh-dr-2786-branch'
